# การใช้งานคำสั่ง Assert เพื่อตรวจหาข้อผิดพลาด

for i in range(10):
    assert i<5 , "Error"
    print(i)